language: java
dist: trusty
script:
- mvn test -DskipTests=true -Dmaven.javadoc.skip=true
export TRAVIS_WORKER_MAX_LOG_LENGTH = 10000000
os:
  - linux
  - osx
  - windows
jdk:
- openjdk14
addons:
apt:
packages:
cache:
directories:
- $HOME/.m2
after_success:
- mvn coveralls:report
  