name: SonarQube Analysis
on:
  # Trigger analysis when pushing in master 
  push:
    branches:
      - master
jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'  
    - name: Build with Maven
      run:
        mvn  -DskipTests --file pom.xml -B package
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: https://sonarcloud.io
        login: ${{ secrets.SONAR_LOGIN }}
        projectKey: ${{secrets.SONAR_PROJECT }}
        projectVersion: ${{ github.workflow }}/${{ github.run_number }}
