name: SonarQube Analysis
on:
  # Trigger analysis when pushing in master 
  push:
    branches:
      - master
jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@master
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: https://sonarcloud.io
        login: ${{ secrets.SONARQUBE_LOGIN }}
        projectKey: ${{secrets.SONARQUBE_PROJECT }}
        projectVersion: ${{ github.workflow }}/${{ github.run_number }}
